name: CI
on:
  push:
    paths:
      - 'app/**'
      - 'helm/**'
  pull_request:


jobs:
  build:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t test-image ./app
    - name: set up helm
      uses: azure/setup-helm@v3
      with:
        version: v3.9.0
    - name: Lint helm Chart
      run: helm lint ./helm/my-python-app
